### ISSUE TITLE
Works well, minor upgrades would be useful

### ISSUE THREAD

**Issue by AbrahamLinqoln** [Katarzyna-Kadziolka/StabilityClient.Net#15]
Thank you for this!
Is it possible to also add .SetCfgScale (Dictates how closely to match prompt).
It would also be handy to specify a custom filename (on SaveImagesToAsync), rather than just the directory.

**Comment by Katarzyna-Kadziolka** [comment]
Both of these functionalities will be in the new version that I will be releasing soon :)

I've added a SaveSingleImageToAsync method where you can specify a file name. If a file with that name already exists in the specified folder, a Guid will be appended to the specified name.

**Comment by Katarzyna-Kadziolka** [comment]
New version (1.3.0) with `SaveSingleImageToAsync` and `.SetCfgScale`  is available now :)
